import { describe, expect, it } from "vitest";
import { decodeTransaction } from "../src/decode/transaction.js";
import { createLedger } from "../bench/ledger.mjs";
import { loadCorpus } from "../bench/shapeTx.mjs";

/**
 * Acceptance on decoded output, not on metadata.
 *
 * The generator's own account of what it produced is not evidence. These
 * assertions run the explorer's real `decodeTransaction` over generated bytes
 * and check what a page would actually render: assets and their quantities,
 * datums, script references, redeemers and addresses.
 */

const parts = loadCorpus();

const ledger = createLedger(parts, {
  seed: 21,
  addresses: 400,
  assets: 60,
  genesisUtxos: 600,
  genesisLovelace: 8_000_000_000n,
  assetsPerOutput: { p50: 1, p95: 3, p99: 6, max: 20 },
  assetQuantity: { p50: 1, p95: 10_000, p99: 1_000_000, max: 9_000_000_000 },
  assetHolderSkew: 1.2,
  addressSkew: 1.2,
  datumRate: 0.3,
  scriptRefRate: 0.2,
  redeemerRate: 0.4,
});

const steps = Array.from({ length: 300 }, () =>
  ledger.spend({ inputs: 2, outputs: 3 }),
).filter((s) => s !== null);

describe("decoded generator output", () => {
  it("produced transactions to inspect", () => {
    expect(steps.length).toBeGreaterThan(200);
  });

  it("the explorer's decoder reads the assets and their quantities", async () => {
    const step = steps.find((s) => s!.created.some((u) => u.assets.size > 0))!;
    const index = step.created.findIndex((u) => u.assets.size > 0);
    const view = await decodeTransaction(step.tx.bytes);
    const rendered = view.outputs[index];
    // AssetMap nests: policy id, then asset name, then quantity.
    const quantities = new Map<string, bigint>();
    for (const [policy, names] of Object.entries(rendered.value.assets)) {
      for (const [name, quantity] of Object.entries(names)) {
        quantities.set(`${policy}${name}`, BigInt(quantity));
      }
    }
    // Every asset the generator says is there is rendered, with its quantity.
    expect(quantities.size).toBe(step.created[index].assets.size);
    for (const [, quantity] of quantities) expect(quantity).toBeGreaterThan(0n);
  });

  it("renders datums and script references at roughly the stated rates", async () => {
    let outputs = 0;
    let datums = 0;
    let scriptRefs = 0;
    for (const step of steps.slice(0, 60)) {
      const view = await decodeTransaction(step!.tx.bytes);
      for (const output of view.outputs) {
        outputs += 1;
        if (output.datum !== null) datums += 1;
        if (output.scriptRef !== null) scriptRefs += 1;
      }
    }
    expect(outputs).toBeGreaterThan(100);
    // 0.3 and 0.2, with sampling room. The point is that they are neither zero
    // nor everything: an unrealized rate reads as a pass on a page that simply
    // never shows the feature.
    expect(datums / outputs).toBeGreaterThan(0.15);
    expect(datums / outputs).toBeLessThan(0.5);
    expect(scriptRefs / outputs).toBeGreaterThan(0.08);
    expect(scriptRefs / outputs).toBeLessThan(0.4);
  });

  it("renders redeemers at roughly the stated rate", async () => {
    let withRedeemers = 0;
    for (const step of steps.slice(0, 60)) {
      const view = await decodeTransaction(step!.tx.bytes);
      if (view.witnesses.redeemerCount > 0) withRedeemers += 1;
    }
    expect(withRedeemers / 60).toBeGreaterThan(0.2);
    expect(withRedeemers / 60).toBeLessThan(0.65);
  });

  it("spreads value over many distinct addresses, concentrated on a few", async () => {
    const perAddress = new Map<string, number>();
    for (const step of steps.slice(0, 120)) {
      const view = await decodeTransaction(step!.tx.bytes);
      for (const output of view.outputs) {
        perAddress.set(output.address, (perAddress.get(output.address) ?? 0) + 1);
      }
    }
    expect(perAddress.size).toBeGreaterThan(50);
    const counts = [...perAddress.values()].sort((a, b) => b - a);
    const top = counts.slice(0, Math.ceil(counts.length * 0.1));
    const share = top.reduce((t, n) => t + n, 0) / counts.reduce((t, n) => t + n, 0);
    expect(share).toBeGreaterThan(0.2);
  });

  it("concentrates holdings on a minority of assets", async () => {
    const perAsset = new Map<string, number>();
    for (const step of steps.slice(0, 120)) {
      const view = await decodeTransaction(step!.tx.bytes);
      for (const output of view.outputs) {
        for (const [policy, names] of Object.entries(output.value.assets)) {
          for (const name of Object.keys(names)) {
            const unit = `${policy}${name}`;
            perAsset.set(unit, (perAsset.get(unit) ?? 0) + 1);
          }
        }
      }
    }
    expect(perAsset.size).toBeGreaterThan(5);
    const counts = [...perAsset.values()].sort((a, b) => b - a);
    const top = counts.slice(0, Math.max(1, Math.ceil(counts.length * 0.2)));
    const share = top.reduce((t, n) => t + n, 0) / counts.reduce((t, n) => t + n, 0);
    expect(share).toBeGreaterThan(0.35);
  });
});
