import type { Metadata } from "next";
import { Breadcrumbs } from "../../components/ui/breadcrumbs";
import { Icon } from "../../components/ui/icons";
import { Callout, PageHeader } from "../../components/ui/primitives";
import { endpointCount, openApiToGroups, type OpenApiDocument } from "../../lib/apiDocs";
import { apiBase, PUBLIC_API_BASE } from "../../lib/env";
import { viewerInit } from "../../lib/viewerInit";

export const metadata: Metadata = {
  title: "API reference",
  description: "Public read-only Midgard Explorer API endpoints and request semantics.",
  alternates: { canonical: "/api-docs" },
};

/** The document is generated by the running backend from the routes it mounts,
 * so this page describes the server a reader is actually talking to rather than
 * whatever the frontend was last told. That also means it has to be fetched per
 * request, not baked in at build time. */
export const dynamic = "force-dynamic";

const CRUMBS = [{ label: "Overview", href: "/" }, { label: "API reference" }];

async function loadDocument(): Promise<OpenApiDocument | null> {
  try {
    const init = await viewerInit();
    const res = await fetch(`${apiBase()}/api/openapi.json`, {
      ...init,
      cache: "no-store",
      signal: AbortSignal.timeout(5_000),
    });
    if (!res.ok) return null;
    return (await res.json()) as OpenApiDocument;
  } catch {
    return null;
  }
}

export default async function ApiDocsPage() {
  const openApi = `${PUBLIC_API_BASE}/api/openapi.json`;
  const document = await loadDocument();
  const groups = document === null ? [] : openApiToGroups(document);

  return (
    <>
      <Breadcrumbs items={CRUMBS} />
      <PageHeader
        title="API reference"
        subtitle="Read-only JSON access to Midgard L2 and the explorer's Cardano L1 index."
        meta={
          document === null ? (
            <span>Contract unavailable</span>
          ) : (
            <span>{endpointCount(groups)} GET endpoints</span>
          )
        }
      >
        <a
          href={openApi}
          className="inline-flex min-h-9 items-center gap-1.5 rounded border border-border-strong px-3 text-sm font-medium text-link hover:bg-surface-2"
        >
          OpenAPI JSON <Icon name="external" size={14} />
        </a>
      </PageHeader>

      <div className="mb-6 grid gap-3 lg:grid-cols-2">
        <Callout tone="info" title="Base URL">
          <code className="break-all font-mono">{PUBLIC_API_BASE}</code>
        </Callout>
        <Callout tone="neutral" title="Response rules">
          {document?.info.description ??
            "Ledger quantities that can exceed JavaScript's safe integer range are decimal strings."}
        </Callout>
      </div>

      {document === null ? (
        <Callout tone="warning" title="The endpoint list could not be loaded">
          This page renders the backend&apos;s own OpenAPI document, and the backend did not answer.
          The contract itself is still at <code className="font-mono">{openApi}</code>.
        </Callout>
      ) : (
        <div className="divide-y divide-border border-y border-border">
          {groups.map((group) => (
            <section
              key={group.name}
              aria-labelledby={`api-${group.name.toLowerCase().replaceAll(" ", "-")}`}
              className="grid gap-4 py-6 lg:grid-cols-[13rem_1fr]"
            >
              <div>
                <h2
                  id={`api-${group.name.toLowerCase().replaceAll(" ", "-")}`}
                  className="text-[15px] font-semibold text-text"
                >
                  {group.name}
                </h2>
              </div>
              <ol className="divide-y divide-border">
                {group.endpoints.map((endpoint) => (
                  <li
                    key={endpoint.path}
                    data-testid="api-endpoint"
                    className="grid gap-2 py-3 first:pt-0 last:pb-0 xl:grid-cols-[minmax(20rem,0.9fr)_1fr] xl:gap-6"
                  >
                    <div className="flex min-w-0 items-start gap-2">
                      <span className="mt-px rounded border border-success/35 bg-success/10 px-1.5 py-px font-mono text-[11px] font-semibold text-success">
                        GET
                      </span>
                      <code className="min-w-0 break-all font-mono text-sm text-text">
                        {endpoint.path}
                      </code>
                    </div>
                    <div>
                      <p className="text-sm text-text-2">{endpoint.summary}</p>
                      {endpoint.parameters.length > 0 ? (
                        <p className="mt-1 mg-micro text-text-3">
                          {endpoint.parameters.join(" · ")}
                        </p>
                      ) : null}
                      {endpoint.rateLimited ? (
                        <p className="mt-1 mg-micro text-warning">Rate limited</p>
                      ) : null}
                    </div>
                  </li>
                ))}
              </ol>
            </section>
          ))}
        </div>
      )}
    </>
  );
}
