import { createHash, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { Client } from "pg";

/**
 * Isolated benchmark and test databases.
 *
 * The guard is ownership, not naming. An earlier version accepted any name
 * ending in `_bench` and had `createDatabase` drop before creating, so a caller
 * passing `customer_data_bench` would have destroyed it. A suffix is a
 * convention anyone can collide with; it is not proof that this harness made
 * the database.
 *
 * Three rules, all enforced:
 *
 *   - **names are generated here, never supplied.** `throwawayName()` returns
 *     `bench_<32 hex>` from a UUID, and both create and drop reject anything
 *     that does not match that exact shape;
 *   - **only a database this harness created and marked is ever dropped.** The
 *     mark is a comment on the database object, checked immediately before the
 *     drop. An unmarked database is refused even with a perfect name;
 *   - **creation never destroys.** `createDatabase` fails if the name is
 *     already taken rather than clearing the way.
 *
 * The live explorer index is never written to and never benchmarked against.
 * `cloneIndex` reads it and writes a frozen copy, and the copy carries a
 * checksum so a later baseline can name the exact data that produced it.
 *
 * The node schema comes from the checked-in fixture rather than the live node,
 * so this is deterministic and needs no running Midgard.
 * `schema-fixture-drift.test.mts` is what keeps the fixture honest.
 */

const FIXTURE = "test/fixtures/schema/midgard-node.sql";

/** Exactly what `throwawayName` produces. Nothing else is addressable. */
const NAME = /^bench_[0-9a-f]{32}$/;

/**
 * Written as a comment on every database this harness creates, and required
 * before any drop. It is what distinguishes "we made this two seconds ago"
 * from "this name happens to look like ours".
 */
const MARKER = "midgard-explorer throwaway benchmark database";

// COMMENT ON DATABASE is a utility statement: it takes no bind parameters, so
// the marker is inlined as a literal. It is a module constant, but assert the
// property the inlining depends on rather than trusting a future edit.
if (MARKER.includes("'")) throw new Error("MARKER must not contain a quote");

/** Names created in this process. Checked alongside the durable marker. */
const created = new Set<string>();

/** A fresh, collision-free, unguessable throwaway name. */
export function throwawayName(): string {
  return `bench_${randomUUID().replace(/-/g, "")}`;
}

/** Refuses any name this harness could not have generated. */
export function assertThrowawayName(name: string): void {
  if (!NAME.test(name)) {
    throw new Error(
      `refusing to operate on "${name}": throwaway names are generated by ` +
        `throwawayName() and match ${NAME.source}`,
    );
  }
}

/**
 * Which PostgreSQL server the harness operates on.
 *
 * Defaults to `POSTGRES_URL`, but the benchmark harness passes
 * `BENCH_POSTGRES_URL` instead. That separation matters: throwaway databases
 * were landing on the same instance as the live Midgard node, so a benchmark
 * competed with the node for CPU and shared buffers and the number it produced
 * described the contention rather than the query.
 */
export function serverUrl(baseUrl?: string): string {
  const base = baseUrl ?? process.env.POSTGRES_URL;
  if (!base) throw new Error("no PostgreSQL URL: set POSTGRES_URL or pass one");
  return base;
}

export function adminUrl(database = "postgres", baseUrl?: string): string {
  const url = new URL(serverUrl(baseUrl));
  url.pathname = `/${database}`;
  return url.toString();
}

async function withAdmin<T>(
  work: (c: Client) => Promise<T>,
  baseUrl?: string,
): Promise<T> {
  const client = new Client({ connectionString: adminUrl("postgres", baseUrl) });
  await client.connect();
  try {
    return await work(client);
  } finally {
    await client.end();
  }
}

/** True only for a database carrying this harness's mark. */
export async function isMarkedThrowaway(
  name: string,
  baseUrl?: string,
): Promise<boolean> {
  if (!NAME.test(name)) return false;
  return withAdmin(async (c) => {
    const { rows } = await c.query<{ mark: string | null }>(
      `SELECT shobj_description(oid, 'pg_database') AS mark
         FROM pg_database WHERE datname = $1`,
      [name],
    );
    return rows.length > 0 && rows[0].mark === MARKER;
  }, baseUrl);
}

/**
 * Drops a database this harness created.
 *
 * Refuses on a name it could not have generated, and refuses on a database
 * carrying no mark, so a name collision cannot turn into data loss.
 */
export async function dropDatabase(name: string, baseUrl?: string): Promise<void> {
  assertThrowawayName(name);
  if (!created.has(name) && !(await isMarkedThrowaway(name, baseUrl))) {
    throw new Error(
      `refusing to drop "${name}": not created by this harness and not marked ` +
        `"${MARKER}"`,
    );
  }
  await withAdmin(async (c) => {
    await c.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [name],
    );
    await c.query(`DROP DATABASE IF EXISTS "${name}"`);
  }, baseUrl);
  created.delete(name);
}

/**
 * Creates a marked throwaway database and returns its name.
 *
 * Takes no name: supplying one is the hazard this module exists to remove.
 * Fails if the generated name is somehow taken rather than dropping it.
 */
export async function createDatabase(baseUrl?: string): Promise<string> {
  const name = throwawayName();
  await withAdmin(async (c) => {
    const { rows } = await c.query(
      `SELECT 1 FROM pg_database WHERE datname = $1`,
      [name],
    );
    if (rows.length > 0) {
      throw new Error(`refusing to create "${name}": it already exists`);
    }
    await c.query(`CREATE DATABASE "${name}"`);
    await c.query(`COMMENT ON DATABASE "${name}" IS '${MARKER}'`);
  }, baseUrl);
  created.add(name);
  return name;
}

/**
 * Runs `work` against a fresh database carrying the node schema, then drops it.
 *
 * The drop runs in a `finally`, so a failing test leaves nothing behind.
 */
export async function withThrowawayNodeDb(
  work: (db: Client) => Promise<void>,
  baseUrl?: string,
): Promise<void> {
  const name = await createDatabase(baseUrl);
  const client = new Client({ connectionString: adminUrl(name, baseUrl) });
  try {
    await client.connect();
    await client.query(stripPsqlMeta(await readFile(FIXTURE, "utf8")));
    await work(client);
  } finally {
    await client.end().catch(() => {});
    await dropDatabase(name, baseUrl);
  }
}

/**
 * Removes psql client meta-commands such as `\restrict`.
 *
 * `pg_dump` emits them and `psql` consumes them, but they are not SQL: sending
 * one through a driver fails with a syntax error at the backslash. The fixture
 * is applied by both psql (in scripts) and by this driver (in tests), so it
 * keeps them and this strips them.
 */
export function stripPsqlMeta(sql: string): string {
  return sql
    .split("\n")
    .filter((line) => !/^\s*\\/.test(line))
    .join("\n");
}

export type Checksum = {
  /** Stable across runs for identical content; changes if any row changes. */
  digest: string;
  tables: Record<string, number>;
  rows: number;
};

/**
 * A content checksum over the tables named, ordered deterministically.
 *
 * Recorded beside every baseline so a measurement can be traced to the exact
 * data that produced it. A number whose dataset cannot be identified is not
 * reproducible, and a baseline that is not reproducible is an anecdote.
 */
export async function checksum(
  db: Client,
  tables: readonly string[],
): Promise<Checksum> {
  const hash = createHash("sha256");
  const counts: Record<string, number> = {};
  let rows = 0;
  for (const table of [...tables].sort()) {
    if (!/^[a-z_][a-z0-9_]*$/.test(table)) {
      throw new Error(`unsafe table name: ${table}`);
    }
    // md5 of the whole row, aggregated in a deterministic order. Cheap, and
    // sensitive to any column changing, which is what a checksum is for.
    const { rows: result } = await db.query<{ n: string; digest: string | null }>(
      `SELECT count(*)::text AS n,
              md5(string_agg(row_digest, '' ORDER BY row_digest)) AS digest
         FROM (SELECT md5(t.*::text) AS row_digest FROM "${table}" t) s`,
    );
    const n = Number(result[0]?.n ?? 0);
    counts[table] = n;
    rows += n;
    hash.update(`${table}:${n}:${result[0]?.digest ?? "empty"}\n`);
  }
  return { digest: hash.digest("hex"), tables: counts, rows };
}
